<?php

declare(strict_types=1);

use App\Http\Controllers\Api\V1\ActivityController;
use App\Http\Controllers\Api\V1\Admin\AdminAccessController;
use App\Http\Controllers\Api\V1\Admin\AdminCalendarController;
use App\Http\Controllers\Api\V1\Admin\AdminEmployeeController;
use App\Http\Controllers\Api\V1\Admin\AdminFailedJobController;
use App\Http\Controllers\Api\V1\Admin\AdminHolidayController;
use App\Http\Controllers\Api\V1\Admin\AdminPermissionController;
use App\Http\Controllers\Api\V1\Admin\AdminRoleController;
use App\Http\Controllers\Api\V1\Admin\AdminSettingController;
use App\Http\Controllers\Api\V1\Admin\AdminSiteChecklistItemController;
use App\Http\Controllers\Api\V1\Admin\AdminStalledInstanceController;
use App\Http\Controllers\Api\V1\Admin\AdminUnclaimedTaskController;
use App\Http\Controllers\Api\V1\Admin\AdminUserController;
use App\Http\Controllers\Api\V1\Admin\AdminWorkflowTemplateController;
use App\Http\Controllers\Api\V1\AttachmentController;
use App\Http\Controllers\Api\V1\AuditLogController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\CorrectiveActionController;
use App\Http\Controllers\Api\V1\CrewLogController;
use App\Http\Controllers\Api\V1\DashboardController;
use App\Http\Controllers\Api\V1\EmployeeController;
use App\Http\Controllers\Api\V1\EnumController;
use App\Http\Controllers\Api\V1\FormulaController;
use App\Http\Controllers\Api\V1\JournalController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\OptionsController;
use App\Http\Controllers\Api\V1\PaymentController;
use App\Http\Controllers\Api\V1\ProjectController;
use App\Http\Controllers\Api\V1\SampleController;
use App\Http\Controllers\Api\V1\SearchController;
use App\Http\Controllers\Api\V1\SiteChecklistItemController;
use App\Http\Controllers\Api\V1\SiteVisitController;
use App\Http\Controllers\Api\V1\StreamController;
use App\Http\Controllers\Api\V1\TaskController;
use App\Http\Controllers\Api\V1\TimeEntryController;
use App\Http\Controllers\Api\V1\TimerController;
use App\Http\Middleware\AuthenticateStream;
use App\Http\Middleware\HandleIdempotencyKey;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::get('stream', StreamController::class)->middleware(AuthenticateStream::class);
    Route::post('auth/login', [AuthController::class, 'login']);

    Route::middleware('auth:sanctum')->group(function (): void {
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::get('auth/me', [AuthController::class, 'me']);
        Route::get('tasks', [TaskController::class, 'index']);
        Route::post('tasks', [TaskController::class, 'store']);
        Route::get('tasks/{id}', [TaskController::class, 'show'])->whereNumber('id');
        Route::post('tasks/{id}/claim', [TaskController::class, 'claim'])->whereNumber('id')->middleware(HandleIdempotencyKey::class);
        Route::post('tasks/{id}/release', [TaskController::class, 'release'])->whereNumber('id');
        Route::post('tasks/{id}/start', [TaskController::class, 'start'])->whereNumber('id');
        Route::post('tasks/{id}/pause', [TaskController::class, 'pause'])->whereNumber('id');
        Route::post('tasks/{id}/resume', [TaskController::class, 'resume'])->whereNumber('id');
        Route::post('tasks/{id}/block', [TaskController::class, 'block'])->whereNumber('id');
        Route::post('tasks/{id}/unblock', [TaskController::class, 'unblock'])->whereNumber('id');
        Route::post('tasks/{id}/complete', [TaskController::class, 'complete'])->whereNumber('id')->middleware(HandleIdempotencyKey::class);
        Route::post('tasks/{id}/comments', [TaskController::class, 'comment'])->whereNumber('id');
        Route::post('tasks/{id}/reassign', [TaskController::class, 'reassign'])->whereNumber('id');
        Route::patch('tasks/{id}/deadline', [TaskController::class, 'updateDeadline'])->whereNumber('id');
        Route::post('tasks/{id}/timer/start', [TimerController::class, 'start'])->whereNumber('id')->middleware(HandleIdempotencyKey::class);
        Route::post('tasks/{id}/timer/stop', [TimerController::class, 'stop'])->whereNumber('id');
        Route::get('timers/active', [TimerController::class, 'active']);
        Route::patch('time-entries/{id}', [TimeEntryController::class, 'update'])->whereNumber('id');
        Route::get('crew-logs', [CrewLogController::class, 'index']);
        Route::post('projects/{id}/crew-logs', [CrewLogController::class, 'store'])->whereNumber('id');
        Route::patch('crew-logs/{id}', [CrewLogController::class, 'update'])->whereNumber('id');
        Route::post('crew-logs/{id}/submit', [CrewLogController::class, 'submit'])->whereNumber('id');
        Route::get('employees', [EmployeeController::class, 'index']);
        Route::get('audit-logs', [AuditLogController::class, 'index']);
        Route::post('tasks/{id}/attachments', [TaskController::class, 'attach'])->whereNumber('id');
        Route::post('tasks/{id}/override-site-block', [TaskController::class, 'overrideSiteBlock'])->whereNumber('id');
        Route::post('attachments', [AttachmentController::class, 'store']);
        Route::get('attachments/{id}', [AttachmentController::class, 'show'])->whereNumber('id');
        Route::delete('attachments/{id}', [AttachmentController::class, 'destroy'])->whereNumber('id');
        Route::get('payments', [PaymentController::class, 'index']);
        Route::get('payments/{id}', [PaymentController::class, 'show'])->whereNumber('id');
        Route::post('projects/{id}/payments', [PaymentController::class, 'storeForProject'])->whereNumber('id');
        Route::get('journals', [JournalController::class, 'index']);
        Route::get('journals/{date}', [JournalController::class, 'show']);
        Route::post('journals/{date}/submit', [JournalController::class, 'submit']);
        Route::post('journals/{date}/reopen', [JournalController::class, 'reopen']);
        Route::get('samples', [SampleController::class, 'index']);
        Route::post('samples', [SampleController::class, 'store']);
        Route::get('samples/{identifier}', [SampleController::class, 'show']);
        Route::get('samples/{identifier}/chain', [SampleController::class, 'chain']);
        Route::post('samples/{identifier}/modification', [SampleController::class, 'modification']);
        Route::post('samples/{identifier}/approval-form', [SampleController::class, 'approvalForm']);
        Route::post('samples/{identifier}/client-decision', [SampleController::class, 'clientDecision']);
        Route::get('samples/{identifier}/formulas', [FormulaController::class, 'index']);
        Route::post('samples/{identifier}/formulas', [FormulaController::class, 'store']);
        Route::post('formulas/{id}/register', [FormulaController::class, 'register'])->whereNumber('id');
        Route::patch('formulas/{id}', [FormulaController::class, 'update'])->whereNumber('id');
        Route::get('site-visits', [SiteVisitController::class, 'index']);
        Route::get('site-visits/{id}', [SiteVisitController::class, 'show'])->whereNumber('id');
        Route::patch('site-visits/{id}', [SiteVisitController::class, 'update'])->whereNumber('id');
        Route::post('site-visits/{id}/measurements', [SiteVisitController::class, 'measurements'])->whereNumber('id')->middleware(HandleIdempotencyKey::class);
        Route::post('site-visits/{id}/submit', [SiteVisitController::class, 'submit'])->whereNumber('id');
        Route::post('site-visits/{id}/readiness', [SiteVisitController::class, 'readiness'])->whereNumber('id');
        Route::get('site-visits/{id}/pdf', [SiteVisitController::class, 'pdf'])->whereNumber('id');
        Route::post('projects/{id}/site-visits', [SiteVisitController::class, 'store'])->whereNumber('id');
        Route::get('projects/{id}/site-visits', [SiteVisitController::class, 'forProject'])->whereNumber('id');
        Route::get('site-checklist-items', [SiteChecklistItemController::class, 'index']);
        Route::get('options/checklist-items', [SiteChecklistItemController::class, 'options']);
        Route::get('options/departments', [OptionsController::class, 'departments']);
        Route::get('options/users', [OptionsController::class, 'users']);
        Route::get('options/employees', [OptionsController::class, 'employees']);
        Route::get('options/clients', [OptionsController::class, 'clients']);
        Route::get('options/projects', [OptionsController::class, 'projects']);
        Route::get('options/blocker-categories', [OptionsController::class, 'blockerCategories']);
        Route::get('corrective-actions', [CorrectiveActionController::class, 'index']);
        Route::get('corrective-actions/{id}', [CorrectiveActionController::class, 'show'])->whereNumber('id');
        Route::patch('corrective-actions/{id}', [CorrectiveActionController::class, 'update'])->whereNumber('id');
        Route::get('activity', [ActivityController::class, 'index']);
        Route::get('notifications', [NotificationController::class, 'index']);
        Route::get('notifications/unread-count', [NotificationController::class, 'unreadCount']);
        Route::post('notifications/read-all', [NotificationController::class, 'markAllRead']);
        Route::post('notifications/{id}/read', [NotificationController::class, 'markRead']);
        Route::get('projects', [ProjectController::class, 'index']);
        Route::post('projects', [ProjectController::class, 'store']);
        Route::get('projects/by-reference/{reference}', [ProjectController::class, 'showByReference']);
        Route::get('projects/{id}', [ProjectController::class, 'show'])->whereNumber('id');
        Route::patch('projects/{id}', [ProjectController::class, 'update'])->whereNumber('id');
        Route::post('projects/{id}/complete', [ProjectController::class, 'complete'])->whereNumber('id');
        Route::post('projects/{id}/cancel', [ProjectController::class, 'cancel'])->whereNumber('id');
        Route::get('projects/{id}/workflow', [ProjectController::class, 'workflow'])->whereNumber('id');
        Route::get('projects/{id}/tasks', [ProjectController::class, 'tasks'])->whereNumber('id');
        Route::get('projects/{id}/payments', [ProjectController::class, 'payments'])->whereNumber('id');
        Route::get('projects/{id}/hours', [ProjectController::class, 'hours'])->whereNumber('id');
        Route::get('projects/{id}/samples', [ProjectController::class, 'samples'])->whereNumber('id');
        Route::get('projects/{id}/activity', [ProjectController::class, 'activity'])->whereNumber('id');
        Route::get('dashboard/control-room', [DashboardController::class, 'controlRoom']);
        Route::get('dashboard/workshop', [DashboardController::class, 'workshop']);
        Route::get('dashboard/site', [DashboardController::class, 'site']);
        Route::get('dashboard/samples', [DashboardController::class, 'samples']);
        Route::get('search', SearchController::class);
        Route::prefix('admin')->group(function (): void {
            Route::get('settings', [AdminSettingController::class, 'index']);
            Route::patch('settings', [AdminSettingController::class, 'update']);
            Route::get('permissions', [AdminPermissionController::class, 'index']);
            Route::get('roles', [AdminRoleController::class, 'index']);
            Route::post('roles', [AdminRoleController::class, 'store']);
            Route::patch('roles/{id}', [AdminRoleController::class, 'update'])->whereNumber('id');
            Route::delete('roles/{id}', [AdminRoleController::class, 'destroy'])->whereNumber('id');
            Route::get('users', [AdminUserController::class, 'index']);
            Route::post('users', [AdminUserController::class, 'store']);
            Route::patch('users/{id}', [AdminUserController::class, 'update'])->whereNumber('id');
            Route::post('users/{id}/roles', [AdminUserController::class, 'syncRoles'])->whereNumber('id');
            Route::get('users/{id}/effective-permissions', [AdminUserController::class, 'effectivePermissions'])->whereNumber('id');
            Route::get('employees', [AdminEmployeeController::class, 'index']);
            Route::post('employees', [AdminEmployeeController::class, 'store']);
            Route::patch('employees/{id}', [AdminEmployeeController::class, 'update'])->whereNumber('id');
            Route::get('holidays', [AdminHolidayController::class, 'index']);
            Route::post('holidays', [AdminHolidayController::class, 'store']);
            Route::patch('holidays/{id}', [AdminHolidayController::class, 'update'])->whereNumber('id');
            Route::delete('holidays/{id}', [AdminHolidayController::class, 'destroy'])->whereNumber('id');
            Route::post('calendar/impact', [AdminCalendarController::class, 'impact']);
            Route::get('workflow-templates', [AdminWorkflowTemplateController::class, 'index']);
            Route::get('workflow-templates/{id}', [AdminWorkflowTemplateController::class, 'show'])->whereNumber('id');
            Route::patch('workflow-templates/{id}', [AdminWorkflowTemplateController::class, 'update'])->whereNumber('id');
            Route::post('workflow-templates/{id}/draft', [AdminWorkflowTemplateController::class, 'createDraft'])->whereNumber('id');
            Route::post('workflow-templates/{id}/publish', [AdminWorkflowTemplateController::class, 'publish'])->whereNumber('id');
            Route::get('site-checklist-items', [AdminSiteChecklistItemController::class, 'index']);
            Route::post('site-checklist-items', [AdminSiteChecklistItemController::class, 'store']);
            Route::patch('site-checklist-items/{id}', [AdminSiteChecklistItemController::class, 'update'])->whereNumber('id');
            Route::get('stalled-instances', [AdminStalledInstanceController::class, 'index']);
            Route::get('unclaimed-tasks', [AdminUnclaimedTaskController::class, 'index']);
            Route::get('failed-jobs', [AdminFailedJobController::class, 'index']);
            Route::post('failed-jobs/{uuid}/retry', [AdminFailedJobController::class, 'retry']);
            Route::get('access/coverage', [AdminAccessController::class, 'coverage']);
        });
        Route::get('enums/{name}', [EnumController::class, 'show']);
    });
});
